/**
 * Drizzle schema. This file is the source of truth for Postgres tables.
 *
 * Edit tables here, then `pnpm db:generate` to write a SQL migration in `drizzle/`,
 * then `pnpm db:migrate` to apply it. `pnpm db:push` doesn't make a migration and
 * instead applies the schema directly to the database.
 *
 * `.references()` is the foreign key. `relations()` below is only for
 * `db.query.*({ with: { ... } })` and does not change the database.
 *
 * Two column styles exist on purpose:
 * - App tables (`post`, `project`) use the callback form `(d) => ({ ... })`.
 *   Object keys become column names, so `createdAt` stays camelCase in SQL.
 * - Better Auth tables pass explicit snake_case names (`"user_id"`). Do not
 *   rename those columns; the auth adapter expects them.
 *
 * `$defaultFn` / `$onUpdate` run in JavaScript when Drizzle issues the write.
 * `.default(false)` is a SQL `DEFAULT`. Raw SQL updates will not bump
 * `$onUpdate` columns.
 */
import { relations } from "drizzle-orm";
import {
  boolean,
  index,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

/**
 * Example table for the `post` router.
 *
 * `generatedByDefaultAsIdentity()` is Postgres identity (`GENERATED BY DEFAULT
 * AS IDENTITY`). `.references(() => user.id)` is the Foreign Key;
 * the callback (t => [...]) is lazy so `user` can be declared later in this file.
 */
export const posts = pgTable(
  "post",
  (d) => ({
    id: d.integer().primaryKey().generatedByDefaultAsIdentity(),
    name: d.varchar({ length: 256 }),
    createdById: d
      .varchar({ length: 255 })
      .notNull()
      .references(() => user.id),
    createdAt: d
      .timestamp({ withTimezone: true })
      .$defaultFn(() => new Date())
      .notNull(),
    updatedAt: d.timestamp({ withTimezone: true }).$onUpdate(() => new Date()),
  }),
  (t) => [
    index("created_by_idx").on(t.createdById),
    index("name_idx").on(t.name),
  ],
);

/**
 * Signed-in app user. Owned by Better Auth; queried by us for membership.
 * Table and column names must stay as generated (`user`, `email_verified`).
 */
export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified")
    .$defaultFn(() => false)
    .notNull(),
  image: text("image"),
  createdAt: timestamp("created_at")
    .$defaultFn(() => /* @__PURE__ */ new Date())
    .notNull(),
  updatedAt: timestamp("updated_at")
    .$defaultFn(() => /* @__PURE__ */ new Date())
    .notNull(),
});

/**
 * Auth session cookie backing store. Better Auth reads and writes this.
 * `onDelete: "cascade"` drops sessions when the user row is deleted.
 */
export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

/**
 * Linked login providers (GitHub OAuth, password, etc.) for Better Auth.
 * `accountId` is the provider (GitHub)'s user id, not our `user.id`.
 */
export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
});

/**
 * Short-lived verification tokens (email verify, magic links). Better Auth owned.
 */
export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").$defaultFn(
    () => /* @__PURE__ */ new Date(),
  ),
  updatedAt: timestamp("updated_at").$defaultFn(
    () => /* @__PURE__ */ new Date(),
  ),
});

/**
 * Postgres enum for `project_role`.
 *
 * `owner` can delete the project.
 * `admin` and `owner` can change settings.
 * `member` is the default for everyone else.
 */
export const projectRole = pgEnum("project_role", ["owner", "admin", "member"]);

/**
 * Project/workspaces for project management
 */
export const projects = pgTable("project", (d) => ({
  id: d.uuid().primaryKey().defaultRandom(),
  name: d.varchar({ length: 255 }).notNull(),
  description: d.text(),
  sprintsEnabled: d.boolean().default(false).notNull(),
  sprintDuration: d.integer().default(2).notNull(),
  sprintStartDate: d.timestamp({ withTimezone: true }),
  createdAt: d
    .timestamp({ withTimezone: true })
    .$defaultFn(() => new Date())
    .notNull(),
  updatedAt: d.timestamp({ withTimezone: true }).$onUpdate(() => new Date()),
}));

/**
 * Project members/roles
 */
export const projectMembers = pgTable(
  "project_member",
  (d) => ({
    projectId: d
      .uuid()
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    userId: d
      .text()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    role: projectRole().default("member").notNull(),
  }),
  (t) => [
    primaryKey({
      name: "project_member_pk",
      columns: [t.projectId, t.userId],
    }),
    index("project_member_user_id_idx").on(t.userId),
  ],
);

/**
 * Relations for the user table.
 *
 * Defining relations here allows us to use them in the database queries. Example:
 * `db.query.user.findFirst({ with: { account: true } })` returns a user with
 * their account data.
 */
export const userRelations = relations(user, ({ many }) => ({
  account: many(account),
  session: many(session),
  projectMembers: many(projectMembers),
}));

/** Relations for the projects table. */
export const projectsRelations = relations(projects, ({ many }) => ({
  members: many(projectMembers), //
}));

/**
 * Relations for the projectMembers table.
 */
export const projectMembersRelations = relations(projectMembers, ({ one }) => ({
  project: one(projects, {
    fields: [projectMembers.projectId],
    references: [projects.id],
  }),
  user: one(user, {
    fields: [projectMembers.userId],
    references: [user.id],
  }),
}));

/** Relations for the account table. */
export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

/** Relations for the session table. */
export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));
